apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: assaf
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat-service-account
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.11.1
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        volumeMounts: 
          - name: config
            mountPath: /etc/filebeat.yml
            readOnly: true
            subPath: filebeat.yml
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 0640
            name: filebeat-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
