apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: assaf
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"

    setup.kibana:
      host: "http://kibana:5601"

    output.logstash:
      hosts: ["logstash:5044"]