apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: assaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.18.1
        ports:
        - containerPort: 5044
        - containerPort: 5000
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: config
        configMap:
          name: logstash-pipeline
