apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: assaf
spec:
  type: LoadBalancer
  selector:
    app: logstash
  ports:
    - name: beats 
      protocol: TCP
      port: 5044
      targetPort: 5044
    - name: jenkins
      protocol: TCP
      port: 5000
      targetPort: 5000