apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: assaf
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
      tcp {
        port => 5000
        codec => json_lines
      }
    }
    filter {
      }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }
